common/models/Booking.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "booking".
 *
 * @property int $id
 * @property int $id_pemesan
 * @property int $id_lapangan
 * @property string $nama
 * @property string $no_hp
 * @property string $tanggal_main
 * @property string $waktu_mulai
 * @property string $waktu_selesai
 * @property string $bukti_transfer
 * @property string $no_rek_transfer
 * @property string $nama_rek_transfer
 * @property int $created_at
 * @property int $updated_at
 * @property int $status
 * @property string $ip
 *
 * @property Lapangan $lapangan
 * @property RefStatus $status0
 * @property User $pemesan
 */
class Booking extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'booking';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_pemesan', 'id_lapangan', 'nama', 'no_hp', 'waktu_mulai', 'waktu_selesai'], 'required'],
            [['id_pemesan', 'id_lapangan', 'created_at', 'updated_at', 'status'], 'integer'],
            [['tanggal_main', 'waktu_mulai', 'waktu_selesai'], 'safe'],
            [['nama'], 'string', 'max' => 100],
            [['no_hp'], 'string', 'min' => 10, 'max' => 16],
            [['bukti_transfer', 'no_rek_transfer', 'nama_rek_transfer'], 'string', 'max' => 128],
            [['id_lapangan'], 'exist', 'skipOnError' => true, 'targetClass' => Lapangan::className(), 'targetAttribute' => ['id_lapangan' => 'id']],
            [['status'], 'exist', 'skipOnError' => true, 'targetClass' => RefStatus::className(), 'targetAttribute' => ['status' => 'id']],
            [['id_pemesan'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['id_pemesan' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_pemesan' => 'Id Pemesan',
            'id_lapangan' => 'Id Lapangan',
            'nama' => 'Nama',
            'no_hp' => 'No Hp',
            'tanggal_main' => 'Tanggal Main',
            'waktu_mulai' => 'Waktu Mulai',
            'waktu_selesai' => 'Waktu Selesai',
            'bukti_transfer' => 'Bukti Transfer',
            'no_rek_transfer' => 'No Rek Transfer',
            'nama_rek_transfer' => 'Nama Rek Transfer',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'status' => 'Status',
            'ip' => 'IP Address',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLapangan()
    {
        return $this->hasOne(Lapangan::className(), ['id' => 'id_lapangan']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus0()
    {
        return $this->hasOne(RefStatus::className(), ['id' => 'status']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPemesan()
    {
        return $this->hasOne(User::className(), ['id' => 'id_pemesan']);
    }

    public static function findByPemesan($id_pemesan)
    {
        return static::findOne(['id_pemesan' => $id_pemesan]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function setIp()
    {
        return $this->ip = Yii::$app->request->userIP;
    }

    public function statusBayar(){
      return $this->status = 2;
    }

    public function statusValid(){
      return $this->status = 10;
    }
}

backend/controllers/BookingController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Booking;
use common\models\BookingSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use common\models\Lapangan;
use yii\helpers\ArrayHelper;
use common\models\SesiWaktu;

/**
 * BookingController implements the CRUD actions for Booking model.
 */
class BookingController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Booking models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BookingSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=10;
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single Booking model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
      return $this->render('view', [
          'model' => $this->findModel($id),
      ]);
    }

    /**
     * Displays a single Booking model.
     * @param integer $id
     * @return mixed
     */
    public function actionTampil($id)
    {
        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "Booking #".$id,
                    'content'=>$this->renderAjax('tampil', [
                        'model' => $this->findModel($id),
                    ]),
                    'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                          Html::a('Validasi',['validasi','id'=>$id],['class'=>'btn btn-primary'])
                ];
        }else{
            return $this->render('tampil', [
                'model' => $this->findModel($id),
            ]);
        }
    }
    /**
     * Updates an existing Booking model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionValidasi($id)
    {
        // $request = Yii::$app->request;
        $model = $this->findModel($id);
        if($model->status != 2){
          // echo "<pre>";print_r($model);exit;
          Yii::$app->session->setFlash('error', [['Error', 'Tidak dapat melakukan validasi']]);
          return $this->redirect('index');
        }

        // if ($model->load(Yii::$app->request->post('submit'))) {

          // if (!$model->validate()) {
          //   Yii::$app->session->setFlash('warning', [['Error', 'Validasi error']]);
          //   return null;
          // }
          // if($model->status == 2){

            $model->status = 10;
            $model->save(false);
            Yii::$app->session->setFlash('success', [['Sukses', 'Berhasil melakukan validasi']]);

            return $this->redirect('index');
          // }


        // }

        // return $this->render('validasi', [
        //   'model' => $model,
        // ]);
    }

    /**
     * Finds the Booking model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Booking the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Booking::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/booking/_columns.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

return [
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    [
        'class'=>'kartik\grid\DataColumn',
        'label' => 'Lapangan',
        'attribute'=>'lapangan.nama',
    ],
    [
        'class'=>'kartik\grid\DataColumn',
        'attribute'=>'nama',
    ],
    [
        'class'=>'kartik\grid\DataColumn',
        'attribute'=>'no_hp',
    ],
    [
        'class'=>'kartik\grid\DataColumn',
        'attribute'=>'tanggal_main',
        'value' => function ($model) {
          if ($model->tanggal_main == 0000-00-00) {
            return "Belum terisi";
            // code
          }
                return date('d-m-Y', strtotime($model->tanggal_main));
         }
    ],
    [
        'class'=>'kartik\grid\DataColumn',
        'attribute'=>'waktu_mulai',
        'value' => function ($model) {
                return date('H:i:s', strtotime($model->waktu_mulai));
         }
    ],
    [
        'class'=>'kartik\grid\DataColumn',
        'attribute'=>'waktu_selesai',
        'value' => function ($model) {
                return date('H:i:s', strtotime($model->waktu_selesai));
         }
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function ($action, $model, $key, $index) {
            return Url::to([$action,'id'=>$key]);
        },
        'template'=>'{view} {validasi}',
        'buttons' => [
            'validasi' => function ($url, $model) {
              if($model->status == 2 ){
                return Html::a('Validasi Pembayaran', ['booking/tampil', 'id' => $model->id], [
                    'class' => 'btn btn-sm btn-primary validate-click',
                    // 'role' => 'modal-remote',
                    'style' => 'width: 150px',
                    'title' => 'Validasi Pembayaran',
                    'data-toggle' => 'tooltip',
                    'role' => 'modal-remote'
                ]);
              }
              return Html::a($model->status0['status_pemesanan'], ['booking/validasi', 'id' => $model->id], [
                  'class' => 'btn btn-sm btn-danger disabled',
                  // 'role' => 'modal-remote',
                  'style' => [
                    'width'=> '150px',
                    'cursor' => 'not-allowed',
                    'pointer-events' => 'none !important',
                  ],
                  'title' => 'status',
                  'data-toggle' => 'tooltip',
              ]);
            },
        ],
        'viewOptions' => [
          'class' => 'btn btn-sm btn-success',
          'title'=>'View',
          'data-toggle'=>'tooltip'
        ],
        // 'confirmOptions' => [
        //   'role' => 'modal-remote',
        //   'class' => 'btn btn-sm btn-warning',
        //   'title' => 'Confirm Pembayaran',
        //   'data-toogle' => 'tooltip'
        // ],
        // 'updateOptions'=>[
        //   'role'=>'modal-remote',
        //   'class' => 'btn btn-sm btn-primary',
        //   'title'=>'Update',
        //   'data-toggle'=>'tooltip'
        // ],
        // 'deleteOptions'=>[
        //   'role'=>'modal-remote','title'=>'Delete',
        //   'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
        //   'class' => 'btn btn-sm btn-danger',
        //   'data-request-method'=>'post',
        //   'data-toggle'=>'tooltip',
        //   'data-confirm-title'=>'Are you sure?',
        //   'data-confirm-message'=>'Are you sure want to delete this item'
        // ],
    ],

];

backend/views/booking/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;
use kartik\widgets\DatePicker;

/* @var $this yii\web\View */
/* @var $model common\models\Booking */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="booking-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id_pemesan')->textInput() ?>

    <?= $form->field($model, "id_lapangan")->widget(Select2::classname(), [
        'data' => $data,
        'options' => ['placeholder' => 'Pilih Lapangan'],
        'pluginOptions' => [
        'allowClear' => true
        ],
    ])->label('Lapangan') ?>

    <?= $form->field($model, 'nama')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'no_hp')->textInput(['maxlength' => true]) ?>

    <!-- < $form->field($model, 'tanggal_main')->textInput() ?> -->

    <?= $form->field($model, 'tanggal_main')
         	->widget(DatePicker::classname(), [
 		    'options' => ['placeholder' => date('Y-m-d H:i')],
 	    	'removeButton' => false,
 		    'pluginOptions' => [
 		        'autoclose'=>true,
 		        'todayHighlight' => true,
 		        'calendarWeeks' => true,
 		        'format' => 'yyyy-mm-dd'
 		    ]
 		]); ?>
    <?= $form->field($model, 'waktu_mulai')->textInput() ?>

    <?= $form->field($model, 'waktu_selesai')->textInput() ?>
<!--
    < $form->field($model, 'bukti_transfer')->textInput(['maxlength' => true]) ?>

    < $form->field($model, 'no_rek_transfer')->textInput(['maxlength' => true]) ?>

    < $form->field($model, 'nama_rek_transfer')->textInput(['maxlength' => true]) ?> -->

    <?= $form->field($model, 'status')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/booking/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\BookingSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="booking-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'id_pemesan') ?>

    <?= $form->field($model, 'id_lapangan') ?>

    <?= $form->field($model, 'nama') ?>

    <?= $form->field($model, 'no_hp') ?>

    <?php // echo $form->field($model, 'tanggal_main') ?>

    <?php // echo $form->field($model, 'waktu_mulai') ?>

    <?php // echo $form->field($model, 'waktu_selesai') ?>

    <?php // echo $form->field($model, 'bukti_transfer') ?>

    <?php // echo $form->field($model, 'no_rek_transfer') ?>

    <?php // echo $form->field($model, 'nama_rek_transfer') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/booking/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Booking */

$this->title = 'Create Booking';
$this->params['breadcrumbs'][] = ['label' => 'Bookings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="booking-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'data' => $data,
    ]) ?>

</div>

backend/views/booking/index.php
<?php
/**
 * @link http://www.a-ray.github.io/
 * @author {{author}} <khori.qq@gmail.com>
 * @License: MIT
 */



use yii\helpers\Html;

use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset;

use yii\bootstrap\Modal;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\BookingSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Pemesanan';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<div class="booking-index">

    <?php Pjax::begin(); ?>
    <?= GridView::widget([
        'dataProvider'=> $dataProvider,
        // 'filterModel' => $searchModel,
        // 'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => 'Belum Ada'],
        'columns' => require(__DIR__.'/_columns.php'),
        'responsive'=>true,
        'pjax' => true
        // 'hover'=>true
    ]); ?>
    <?php Pjax::end(); ?>
</div>


<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

<!-- <a class="btn btn-info validate-click" value="<yii\helpers\Url::to(['sites/data-kategori']) ?>">Info Kategori</a> -->

backend/views/booking/tampil.php
<?php

use yii\widgets\DetailView;
/* @var $this yii\web\View */
/* @var $model app\models\Customer */
$this->title = 'Validasi pesanan';

?>

<div class="validate-view">


    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'nama',
            'no_hp',
            // 'bukti_transfer',
            [
                'label'=>'Bukti Transfer',
                'attribute'=>'bukti_transfer',
                'value' => Yii::getAlias('@sipenful/'. $model->bukti_transfer),
                'format' => ['image', ['width' => '200px', 'height' => 'auto']],
            ],

        ],
    ]) ?>

</div>

backend/views/booking/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Booking */

$this->title = 'Update Booking: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Bookings', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="booking-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'data' => $data,
    ]) ?>

</div>

backend/views/booking/validasi.php
<?php

use kartik\form\ActiveForm;

use kartik\widgets\SwitchInput;

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\bootstrap\Modal;
/* @var $this yii\web\View */
/* @var $model app\models\Customer */
$this->title = 'Validasi pesanan';

$js = <<<js
$('.validate-click').click(function () {
     $('#validate-modal')
         .modal('show')
         .find('#validateModalContent')
         .load($(this).attr('value'));
 });
js;

$this->registerJs($js);

?>


<?php
  Modal::begin([
      'header'=>'<h4>Validasi Pemesanan</h4>',
      'id'=>'validate-modal',
      'size'=>'modal-lg'
  ]);

  echo "<div id='validateModalContent'></div>";

  Modal::end();
?>

<div class="validate-view">


    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'nama',
            'no_hp',
            // 'bukti_transfer',
            [
                'label'=>'Bukti Transfer',
                'attribute'=>'bukti_transfer',
                'value' => Yii::getAlias('@sipenful/'. $model->bukti_transfer),
                'format' => ['image'],
            ],

        ],
    ]) ?>

<?php  ActiveForm::begin([
    'id' => 'validasi-form',
]) ?>
    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Submit', ['class' => 'btn btn-primary'], ['name'=>'submit']) ?>
        </div>
    </div>
    <?php ActiveForm::end() ?>

    <div class="form-group">
      <?= Html::a('Validate',['booking/validasi', 'id' => $model->id] ,
        ['class'=>'btn btn-success']
      )?>

    </div>

</div>

backend/views/booking/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Booking */

$this->title = 'Booking #'. $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Bookings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="booking-view">

    <h1>Detail</h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            // 'id',
            // 'id_pemesan',
            [
              'label' => 'Lapangan',
              'attribute'=> 'lapangan.nama',
            ],

            'nama',
            'no_hp',
            [
                'class'=>'kartik\grid\DataColumn',
                'attribute'=>'tanggal_main',
                'value' => function ($model) {
                  if ($model->tanggal_main == 0000-00-00) {
                    return "Belum terisi";
                    // code
                  }
                        return date('d-m-Y', strtotime($model->tanggal_main));
                 }
            ],
            [
                'class'=>'kartik\grid\DataColumn',
                'label' => 'Mulai Main',
                'attribute'=>'waktu_mulai',
                'value' => function ($model) {
                        return date('H:i:s', strtotime($model->waktu_mulai));
                 }
            ],
            [
                'class'=>'kartik\grid\DataColumn',
                'label' => 'Selesai Main',
                'attribute'=>'waktu_selesai',
                'value' => function ($model) {
                        return date('H:i:s', strtotime($model->waktu_selesai));
                 }
            ],
            [
                'label'=>'Bukti Transfer',
                'attribute'=>'bukti_transfer',
                'value' => Yii::getAlias('@sipenful/'. $model->bukti_transfer),
                'format' => ['image', ['width' => '300px', 'height' => 'auto']],
            ],
            'no_rek_transfer',
            'nama_rek_transfer',
            // 'created_at',
            // 'updated_at',
            'status0.status_pemesanan',
            'ip',
        ],
    ]) ?>


</div>